# Generated by Django 4.1.2 on 2022-11-11 20:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_jwt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_online',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
